import { NextResponse } from "next/server";
import Stripe from "stripe";
import User from "@/models/User";
import dbConnect from "@/lib/dbConnect.js";
import { getUserFromToken } from "@/lib/auth";

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);

export async function POST(request) {
    try {
        await dbConnect();
        const decoded = await getUserFromToken(request);
        const userId = decoded?.id;
        
        if (!userId) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const { sessionId } = await request.json();
        
        if (!sessionId) {
            return NextResponse.json({ error: "No session ID provided" }, { status: 400 });
        }

        // Retrieve the checkout session from Stripe
        const session = await stripe.checkout.sessions.retrieve(sessionId);
        console.log("Stripe Verification Session:", { id: session.id, status: session.status, payment_status: session.payment_status, subscription: session.subscription });
        
        // If payment was successful, activate the subscription
        if (session.status === 'complete' || session.payment_status === 'paid') {
            const subscriptionId = session.subscription;
            
            if (subscriptionId) {
                const subscription = await stripe.subscriptions.retrieve(subscriptionId);
                
                let endDate = new Date();
                if (subscription && subscription.current_period_end) {
                    endDate = new Date(subscription.current_period_end * 1000);
                } else {
                    console.log("Warning: current_period_end missing from Stripe subscription. Using 30-day fallback.");
                    endDate.setDate(endDate.getDate() + 30);
                }
                
                await User.findByIdAndUpdate(userId, {
                    subscriptionStatus: 'active',
                    subscriptionId: subscriptionId,
                    stripeCustomerId: session.customer,
                    subscriptionEndDate: endDate
                });
                
                console.log(`User ${userId} activated via verification endpoint. End Date: ${endDate}`);
                return NextResponse.json({ success: true, message: "Subscription activated successfully" });
            } else {
                console.log("No subscription ID found in session.");
                return NextResponse.json({ success: false, message: "Payment successful, but no subscription was generated by Stripe." }, { status: 400 });
            }
        }
        
        return NextResponse.json({ success: false, message: `Payment not completed. Status: ${session.status}, Payment Status: ${session.payment_status}` }, { status: 400 });
    } catch (error) {
        console.error("Session verification error:", error);
        return NextResponse.json({ message: error.message || "Failed to verify session internally" }, { status: 500 });
    }
}
